ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE projects ALTER COLUMN id DROP DEFAULT;
ALTER TABLE projects ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE memberships ALTER COLUMN id DROP DEFAULT;
ALTER TABLE memberships ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE tasks ALTER COLUMN id DROP DEFAULT;
ALTER TABLE tasks ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

DROP SEQUENCE users_seq;
DROP SEQUENCE projects_seq;
DROP SEQUENCE memberships_seq;
DROP SEQUENCE tasks_seq;
